---
# ansible-playbook _passwords.yml --ask-vault-pass

- name: _passwords.yml
  hosts: all:!laptops:!docker_containers:!ubuntu_servers
  include_vars: vaults/_passwords.yml
  no_log: true
  # become: yes
  # become_method: sudo

  tasks:
#  - name: check if user 'tom' exists
#    shell: id -u tom
#    register: tom_exists
#    ignore_errors: true

  - name: update 'tom' passwd
    user:
      name: tom
      password: "{{ vault_tompwd }}"
      update_password: always
#    when: tom_exists.rc == 0

#  - name: create user 'tom'
#    user:
#      name: tom
#      password: "{{ vault_tompwd }}"
#      shell: /bin/zsh
#      uid: 1000
#      groups: sudo
#    when: tom_exists.rc != 0

#  - name: update 'root' passwd
#    user:
#      name: root
#      password: "{{ vault_rootpwd }}"
#      update_password: always
...
