---
- name: check reachable archivebox_servers
  hosts: archivebox_servers
  gather_facts: no
  become: false
  tasks:
    - command: ping -c1 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true
      failed_when: false
    - group_by: key=reachable
      when: "ping_result.rc == 0"

- name: archivebox_servers.yml
  # hosts: archivebox_servers
  hosts: reachable
  gather_facts: no

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }

  tasks:
    - name: Install packages
      apt:
        pkg:
        - python3
        - python3-pip
        - python3-distutils
        - git
        - wget
        - curl
        - youtube-dl
        - chromium
...
