---
- name: archivebox_servers.yml
  hosts: archivebox_servers

  roles:
    - common
    - postfix
    - rsyslog
    - tmux

  tasks:
    - name: Install packages
      apt:
        pkg:
        - python3
        - python3-pip
        - python3-distutils
        - git
        - wget
        - curl
        - youtube-dl
        - chromium
...
