---
- name: docker_servers.yml
  hosts: docker_servers

  vars:
    docker_users:
      - tom

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - geerlingguy.docker
...
