---
- name: k3s_servers.yml
  hosts: k3s_cluster
  gather_facts: no

  roles:
    - common
    - postfix
    # - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }

  tasks:
    - name: Install packages
      apt:
        pkg:
        - nfs-common
        - curl
...
