---
- name: k3s_servers.yml
  hosts: k3s_cluster

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }

  tasks:
    - name: Install packages
      apt:
        pkg:
        - nfs-common
...
