---
- name: media_servers.yml
  hosts: media_servers

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }
...
