---
- name: plex_servers.yml
  hosts: plex_servers
  gather_facts: no

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }

  tasks:
    - name: Add plex apt-key
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key

    - name: Add plex apt repository
      apt_repository:
        repo: 'deb https://downloads.plex.tv/repo/deb public main'
        filename: plex
        update_cache: yes

    - name: Install packages
      apt:
        pkg:
        - cifs-utils
        - nfs-common
        - plexmediaserver
...
