---
- name: pxe_servers.yml
  hosts: pxe_servers

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }

  tasks:
    - name: Install packages
      apt:
        pkg:
        - dnsmasq
        - pxelinux
        - syslinux-common
...
