---
- name: pxe_servers.yml
  hosts: pxe_servers
  gather_facts: no

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }

  tasks:
    - name: Install packages
      apt:
        pkg:
        - dnsmasq
        - pxelinux
        - syslinux-common
...
