---
- name: samba_servers.yml
  hosts: samba_servers
  gather_facts: no

  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }
    - samba
...
