---
# site.yml

# - import_playbook: backup_network_devices.yml
# - import_playbook: archivebox_servers.yml
- import_playbook: db_servers.yml
- import_playbook: debian_servers.yml
- import_playbook: docker_servers.yml
# - import_playbook: duplicacy_clients.yml
# - import_playbook: duplicacy_servers.yml
- import_playbook: hass_servers.yml
- import_playbook: media_servers.yml
# - import_playbook: nextcloud_servers.yml
- import_playbook: pihole_servers.yml
- import_playbook: plex_servers.yml
- import_playbook: postgres_servers.yml
- import_playbook: prometheus_servers.yml
- import_playbook: proxmox_servers.yml
# - import_playbook: pxe_servers.yml
# - import_playbook: samba_servers.yml
- import_playbook: ubuntu_servers.yml
- import_playbook: web_servers.yml
# - import_playbook: zoneminder_servers.yml
...
