---
- name: ubuntu_servers.yml
  hosts: ubuntu_servers
  gather_facts: no

  user: tom
  become: yes
  roles:
    - common
    - postfix
    - rsyslog
    - { role: tmux, username: tom }
    - { role: tmux, username: root }
    - { role: user-config, username: tom }
    - { role: user-config, username: root }
...
