---
# tasks file for user-config

- set_fact:
    home_dir: "/home"
- set_fact:
    home_dir: ""
  when: username == "root"

- name: copy grml-config files for user '{{ username }}'
  copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    follow: no       # overwrite existing links with files
    force: yes
  loop:
    - .screenrc
    - .tmux.conf
    - .vimrc
    - .zshrc
    - ~/.zshrc.local

- name: copy .config files for user '{{ username }}'
  copy:
    src: "~/.config/{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/.config/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    local_follow: yes
    force: yes
    backup: yes
  loop:
    - liquidpromptrc

- name: copy .config/mc files for user '{{ username }}'
  copy:
    src: "~/.config/mc/{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/.config/mc/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    local_follow: yes
    force: yes
    backup: yes
  loop:
    - ini

- name: copy .local/share files for user '{{ username }}'
  copy:
    src: "~/.local/share/{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/.local/share/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    local_follow: yes
    force: yes
    backup: yes
  loop:
    - liquidprompt
    - z.sh
...
