---
# tasks file for user-config

- set_fact:
    home_dir: "/home"
- set_fact:
    home_dir: ""
  when: username == "root"

- name: copy grml-config files for user '{{ username }}'
  copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    follow: no       # overwrite existing links with files
    force: yes
  loop:
    - .screenrc
    - .tmux.conf
    - .vimrc
    - .zshrc
    - ~/.zshrc.local

- name: copy .config files for user '{{ username }}'
  copy:
    src: "~/.config/{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/.config/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    local_follow: yes
    force: yes
    backup: yes
  loop:
    - liquidpromptrc

- name: copy .config/mc files for user '{{ username }}'
  copy:
    src: "~/.config/mc/{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/.config/mc/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    local_follow: yes
    force: yes
    backup: yes
  loop:
    - ini

- name: mc message_visible
  lineinfile:
    path: ~/.config/mc/ini
    regexp: '^message_visible=true'
    line: 'message_visible=1'
    backup: no

- name: mc keybar_visible
  lineinfile:
    path: ~/.config/mc/ini
    regexp: '^keybar_visible='
    line: 'keybar_visible=1'
    backup: no

- name: mc xterm_title
  lineinfile:
    path: ~/.config/mc/ini
    regexp: '^xterm_title='
    line: 'xterm_title=1'
    backup: no

- name: mc menubar_visible
  lineinfile:
    path: ~/.config/mc/ini
    regexp: '^menubar_visible='
    line: 'menubar_visible=1'
    backup: no

- name: mc free_space
  lineinfile:
    path: ~/.config/mc/ini
    regexp: '^free_space='
    line: 'free_space=1'
    backup: no

- name: mc command_prompt
  lineinfile:
    path: ~/.config/mc/ini
    regexp: '^command_prompt='
    line: 'command_prompt=1'
    backup: no

- name: copy .local/share files for user '{{ username }}'
  copy:
    src: "~/.local/share/{{ item }}"
    dest: "{{ home_dir }}/{{ username }}/.local/share/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    local_follow: yes
    force: yes
    backup: yes
  loop:
    - liquidprompt
    - z.sh
...
