---
# tasks file for tmux

- name: Install packages
  apt:
    pkg:
    - tmux
    - fonts-powerline
    - mosh

- set_fact:
    home_dir: "/home"
- set_fact:
    home_dir: ""
  when: username == "root"

- name: Autostart tmux upon zsh login shell for '{{ username }}'
  blockinfile:
    path: "{{ home_dir }}/{{ username }}/.zprofile"
    block: |
      # inspired by https://jpmens.net/2019/04/28/automatically-start-or-attach-tmux-in-ssh-session/
      test -n "$SSH_TTY" && {
          TMUX_TMPDIR=$HOME/tmp
          export TMUX_TMPDIR
          test -d $TMUX_TMPDIR || mkdir -p $TMUX_TMPDIR
          command -v tmux &> /dev/null && test -z "$TMUX" -a -n "$SSH_CONNECTION" && exec tmux new -As default
      }
    backup: yes
    create: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    insertbefore: BOF

- name: Autostart tmux upon login shell for 'root'
  blockinfile:
    path: /root/.profile
    block: |
      # inspired by https://jpmens.net/2019/04/28/automatically-start-or-attach-tmux-in-ssh-session/
      test -n "$SSH_TTY" && {
          TMUX_TMPDIR=$HOME/tmp
          export TMUX_TMPDIR
          test -d $TMUX_TMPDIR || mkdir -p $TMUX_TMPDIR
          command -v tmux &> /dev/null && test -z "$TMUX" -a -n "$SSH_CONNECTION" && exec tmux new -As default
      }
    backup: yes
    insertafter: "# ~/.profile: executed by Bourne-compatible login shells."
...
